source 'http://rubygems.org'

gem 'haml'
gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-archives'
gem 'jemoji'
gem 'thor'
gem 'csv'
gem 'ostruct'
gem 'logger'
gem 'benchmark'
gem 'webrick'
gem 'jekyll-postcss'

group :test, :development do
  gem 'html-proofer'
  gem 'nokogiri'
  gem 'pry'
  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
  gem 'sinatra-cross_origin'
end
