#!/bin/bash

# Function to show usage
show_usage() {
    echo "Usage: ./new <type> <title>"
    echo "For books: ./new book \"<author_last>\" \"<title>\""
    echo
    echo "Available types:"
    echo "  post     - Create a new blog post"
    echo "  link     - Create a new link post"
    echo "  micro    - Create a new micro post"
    echo "  book     - Create a new book entry"
    echo
    echo "Examples:"
    echo "  ./new post \"My New Blog Post\""
    echo "  ./new link \"Interesting Article\""
    echo "  ./new micro video \"My Favorite Song\""
    echo "  ./new book \"Eliot\" \"Notes Towards the Definition of Culture\""
    exit 1
}

# Check if no arguments provided
if [ $# -eq 0 ]; then
    show_usage
fi

# Get the type
type=$1
shift

case $type in
    "book")
        if [ $# -lt 2 ]; then
            echo "Error: Please provide both author_last and title for book entries"
            show_usage
        fi
        author_last=$1
        shift
        title="$@"
        echo "Debug: Creating book entry with author: $author_last, title: $title"
        ruby script/book.rb "$author_last" "$title"
        ;;
    "post"|"link")
        title="$@"
        if [ -z "$title" ]; then
            echo "Error: Please provide a title"
            show_usage
        fi
        ruby script/post.rb "$type" "$title"
        ;;
    "micro")
        title="$@"
        if [ -z "$title" ]; then
            echo "Error: Please provide a title"
            show_usage
        fi
        # For micro posts, we need to extract the micro type from the title
        micro_type=$(echo "$title" | cut -d' ' -f1)
        micro_title=$(echo "$title" | cut -d' ' -f2-)
        ruby script/micro.rb "$micro_type" "$micro_title"
        ;;
    *)
        echo "Error: Unknown type '$type'"
        show_usage
        ;;
esac 