local_backend: true

site_url: https://www.colemanm.org
logo_url: /images/favicon.ico

backend:
  name: git-gateway
  branch: master

media_folder: "/images/post-images"
public_folder: "/images/post-images"

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: { field: "layout", value: "post" }
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Description", name: "description", widget: "string", hint: "Text description for metadata" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Categories", name: "categories", widget: "string", default: "blog" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "link"
    label: "Link"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: { field: "layout", value: "link" }
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "link"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Target", name: "target", widget: "string" }      
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Categories", name: "categories", widget: "string", default: "blog" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - label: "Links"
        name: "links"
        label_singular: "Link"
        widget: "list"
        collapsed: false
        fields:
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Icon", name: "icon", widget: "string" }
  
  - name: "book"
    label: "Book"
    folder: "_books"
    create: true
    slug: "{{author_last}}-{{title}}"
    filter: { field: "layout", value: "book" }
    sortable_fields: [ "date_started", "date_completed", "title", "author_last" ]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "book"}
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Author Last Name", name: "author_last", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Fiction", value: "fiction" }
          - { label: "Nonfiction", value: "nonfiction" }
      - { label: "Cover", name: "cover", widget: "boolean" , default: true }
      - { label: "Series", name: "series", widget: "string" }
      - { label: "Part", name: "part", widget: "number" }
      - label: "Genres"
        name: "genres"
        widget: "list"
        collapsed: false
        fields:
          - { label: "Genre", name: "genre", widget: "string" }
      - { label: "ISBN", name: "isbn", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number" }
      - { label: "Pages", name: "pages", widget: "number" }
      - label: "Format"
        name: "format"
        widget: "select"
        options:
          - { label: "Paperback", value: "paperback" }
          - { label: "Hardcover", value: "hardcover" }
          - { label: "Audiobook", value: "audiobook" }
          - { label: "Kindle", value: "kindle" }
      - { label: "Publish Year", name: "publish_year", widget: "number" }
      - { label: "Publisher", name: "publisher", widget: "string" }
      - { label: "Date Started", name: "date_started", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Date Completed", name: "date_completed", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Goodreads ID", name: "goodreads_id", widget: "string" }
      - { label: "Amazon Link", name: "amazon_link", widget: "string" }
  