#!/bin/sh

set -e

title () {
  echo ""
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo ""
}

export CI=1

title "Checking site..."
bundle exec rake test

title "checking ruby"
bundle exec rubocop -D -S

title "Cleaning up..."
rm -Rf _site
